//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mikhalevpr5.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class telecommunicationEntities1 : DbContext
    {
        public telecommunicationEntities1()
            : base("name=telecommunicationEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AuthInfo> AuthInfo { get; set; }
        public virtual DbSet<ClientEquipment> ClientEquipment { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<ClientServices> ClientServices { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Equipment> Equipment { get; set; }
        public virtual DbSet<EquipmentExpenses> EquipmentExpenses { get; set; }
        public virtual DbSet<MonthlyCharges> MonthlyCharges { get; set; }
        public virtual DbSet<PasswordRecovery> PasswordRecovery { get; set; }
        public virtual DbSet<RegistrationConfirmation> RegistrationConfirmation { get; set; }
        public virtual DbSet<Requests> Requests { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Services> Services { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
