//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mikhalevpr5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonthlyCharges
    {
        public int ChargeID { get; set; }
        public long ClientID { get; set; }
        public System.DateTime ChargeMonth { get; set; }
        public decimal Amount { get; set; }
    
        public virtual Clients Clients { get; set; }
    }
}
