//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mikhalevpr5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistrationConfirmation
    {
        public int ConfirmationID { get; set; }
        public long ClientID { get; set; }
        public string ConfirmationCode { get; set; }
        public System.DateTime ExpirationDate { get; set; }
    
        public virtual Clients Clients { get; set; }
    }
}
