//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mikhalevpr5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requests
    {
        public long RequestID { get; set; }
        public long ClientID { get; set; }
        public long ServiceID { get; set; }
        public System.DateTime RequestDate { get; set; }
        public long StatusID { get; set; }
        public long EmployeeID { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Services Services { get; set; }
        public virtual Status Status { get; set; }
    }
}
